# Default values for chart-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "1.23"

  ingress:
  enabled: true
  hosts:
    - host: srv-dev.test
      paths:
        - path: /
          pathType: Prefix
